- name: Проверка, создан ли уже namespace Argocd
  ansible.builtin.command: "kubectl get ns argocd"
  register: argocd_ns_check
  failed_when: false
  changed_when: false

- name: Создание namespace для ArgoCD
  ansible.builtin.command: "kubectl create namespace argocd"
  when: argocd_ns_check.rc != 0
  changed_when: true

- name: Развертывание манифеста argoCD
  ansible.builtin.command: >
    kubectl apply -n argocd -f
    https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    --server-side=true --force-conflicts
  changed_when: true

- name: Ожидание запуска основных подов ArgoCD
  ansible.builtin.command: >
    kubectl get pods -n argocd -l app.kubernetes.io/name=argocd-server
    -o jsonpath='{.items[*].status.phase}'
  register: argocd_pods_status
  changed_when: false

- name: Перевод веб-интерфейса ArgoCD в режим NodePort
  ansible.builtin.command:
    cmd: "kubectl patch svc argocd-server -n argocd -p '{\"spec\":{\"type\":\"NodePort\",\"ports\":[{\"port\":80,\"nodePort\":30080}]}}'"
  changed_when: true

- name: Создание временного файла манифеста root-apps
  ansible.builtin.copy:
    dest: /tmp/root-apps.yaml
    mode: '0644'
    content: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: opencost-grafana-dashboard
        namespace: monitoring
        labels:
          grafana_dashboard: "1"
        annotations:
          grafana.org/folder: "OpenCost"
      data:
        opencost-dashboard.json: |-
          {{ lookup('file', 'apps/opencost-dashboard.json') | indent(10) }}
  changed_when: false
- name: Применение манифеста root-apps в Kubernetes
  ansible.builtin.command: kubectl apply -f /tmp/root-apps.yaml
  changed_when: true

- name: Создание временного файла манифеста дашборда OpenCost
  ansible.builtin.copy:
    dest: /tmp/opencost-dashboard.yaml
    mode: '0644'
    content: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: opencost-grafana-dashboard
        namespace: monitoring
        labels:
          grafana_dashboard: "1"
      data:
        opencost-dashboard.json: |
          {{ lookup('file', 'apps/opencost-dashboard.json') | indent(10) }}
  changed_when: false

- name: Применение манифеста дашборда OpenCost в Kubernetes
  ansible.builtin.command: kubectl apply -f /tmp/opencost-dashboard.yaml
  changed_when: true

