- name: Проверка, создан ли уже namespace Argocd
  ansible.builtin.command: "kubectl get ns argocd"
  register: argocd_ns_check
  failed_when: false
  changed_when: false

- name: Создание namespace для ArgoCD
  ansible.builtin.command: "kubectl create namespace argocd"
  when: argocd_ns_check.rc != 0

- name: Развертывание манифеста argoCD
  ansible.builtin.command: >
    kubectl apply -n argocd -f
    https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    --server-side=true --force-conflicts

- name: Ожидание запуска основных подов ArgoCD
  ansible.builtin.command: >
    kubectl get pods -n argocd -l app.kubernetes.io/name=argocd-server
    -o jsonpath='{.items[*].status.phase}'
  register: argocd_pods_status
  changed_when: false

- name: Перевод веб-интерфейса ArgoCD в режим NodePort
  ansible.builtin.command: >
    kubectl patch svc argocd-server -n argocd -p
    '{\"spec\": {\"type\": \"NodePort\", \"ports\": [{\"port\": 80, \"nodePort\": 30080}]}}'
