apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/qwizzy12/finOPS-pet"
    chart: kube-prometheus-stack
    targetRevision: 61.3.0
    helm:
      values: |
        grafana:
          service:
            type: NodePort
            nodePort: 30090
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
