apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://opencost.github.io/opencost-helm-chart'
    chart: opencost
    targetRevision: 1.15.0
    helm:
      values: |
        opencost:
          extraEnv:
            - name: CLOUD_PROVIDER
              value: "custom"
          exporter:
            cloudProviderApiKey: "disabled"
            defaultClusterId: "yandex-cloud-cluster"
          customPricing:
            enabled: true
            provider: "custom"
            costModel:
              description: "Yandex Cloud Ruble Prices"
              CPU: "1.25"
              RAM: "0.20"
              storage: "0.05"
          prometheus:
            internal:
              enabled: false
            external:
              enabled: true
              url: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: opencost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

