apiVersion: v1
kind: ConfigMap
metadata:
  name: opencost-default-pricing
  namespace: opencost
data:
  default.json: |
    {
      "description": "Yandex Cloud",
      "CPU": "1.25",
      "RAM": "0.20",
      "storage": "0.05"
    }
