apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opencost-monitor
  namespace: opencost
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: opencost
  endpoints:
  - port: http-metrics
    interval: 30s
    path: /metrics

