apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://opencost.github.io/opencost-helm-chart'
    chart: opencost
    targetRevision: 1.15.0
    helm:
      values: |
        opencost:
          cloudProvider: "custom"
          extraEnv:
            - name: CLOUD_PROVIDER
              value: "custom"
          exporter:
            cloudProviderApiKey: "disabled"
            defaultClusterId: "yandex-cloud-cluster"
          customPricing:
            enabled: true
            provider: "custom"
          pricingSrc: "default.json"
          pricingVolume:
            configMap:
              name: opencost-pricing
          metrics:
            serviceMonitor:
              enabled: true
          prometheus:
            internal:
              enabled: false
            external:
              enabled: true
              url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: opencost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
