apiVersion: v1
kind: ConfigMap
metadata:
  name: opencost-default-pricing
  namespace: opencost
data:
  default.json: |
    {
      "CPU": "0.022",
      "RAM": "0.005",
      "GPU": "0.95",
      "storage": "0.00015",
      "zoneNetworkEgress": "0.01",
      "regionNetworkEgress": "0.01",
      "internetNetworkEgress": "0.12",
      "forwardingrule": "0.0",
      "lbIngressDataCost": "0.0"
    }

