apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://opencost.github.io/opencost-helm-chart'
    chart: opencost
    targetRevision: 1.15.0
    helm:
      values: |
        opencost:
          exporter:
            cloudProviderApiKey: "disabled"
            defaultClusterId: "yandex-cloud-cluster"
            cloudCost:
              enabled: false
        livenessProbe:
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            initialDelaySeconds: 120
            periodSeconds: 10
          customPricing:
            enabled: true
            provider: "custom"

            costModel:
              description: "Yandex Cloud RUB"
              cpu: "1.25"
              ram: "0.20"
              storage: "0.05"
          prometheus:
            internal:
              enabled: false
            external:
              url: "http://prometheus-operated.monitoring.svc.cluster.local:9090"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: opencost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
